### ISSUE TITLE
Problem doing 'Archive research' from works#show

### ISSUE THREAD

**Issue by hading** [BibApp/BibApp#18]
Initially reported by Mark MacGillivray to Bill Ingram:

---

Hi Bill,

I have an error coming up on my test install when I try to upload an attachment. I am hoping to use this functionality as a template for building the sword 2 demo, so can you give me any pointers?

I am using the version from the BibApp repo, downloaded fresh on Thursday night. My test install is at bibapp.cottagelabs.comhttp://bibapp.cottagelabs.com, I am just using the default admin user and pw (admin@example.commailto:admin@example.com,bibapp)

When following the "Archive research" link - which goes to /works/1/attachments/new I get a timeout. The log shows the following
error:
# 

Started GET "/works/1/attachments/new" for 94.173.15.148 at Sun May 29
11:21:18 +0100 2011
  [1m [36mSQL (0.6ms) [0m   [1mdescribe `roles_users` [0m   [1m [35mSQL (0.5ms) [0m  describe `roles_users`  Processing by AttachmentsController#new as HTML
 Parameters: {"work_id"=>"1"}
  [1m [36mUser Load (0.1ms) [0m   [1mSELECT `users`.\* FROM `users` WHERE `users`.`id` = 1 LIMIT 1 [0m   [1m [35mCACHE (0.0ms) [0m  SELECT `users`.\* FROM `users` WHERE `users`.`id` = 1 LIMIT 1   [1m [36mWork Load (0.1ms) [0m   [1mSELECT `works`.\* FROM `works` WHERE `works`.`id` = 1 LIMIT 1 [0m   [1m [35mCACHE (0.0ms) [0m  SELECT `works`.\* FROM `works` WHERE `works`.`id` = 1 LIMIT 1   [1m [36mSQL (0.6ms) [0m   [1mdescribe `roles_users` [0m   [1m [35mRole Load (0.1ms) [0m  SELECT `roles`.\* FROM `roles` WHERE (name = 'admin' and authorizable_type = 'System' and authorizable_id IS NULL) LIMIT 1   [1m [36mRole Load (0.1ms) [0m   [1mSELECT `roles`.`id` FROM `roles` INNER JOIN `roles_users` ON `roles`.id = `roles_users`.role_id WHERE `roles`.`id` = 1 AND (`roles_users`.user_id = 1 ) LIMIT 1 [0m   [1m [35mBookWhole Load (0.1ms) [0m  SELECT `works`.\* FROM `works` WHERE `works`.`type` = 'BookWhole' AND `works`.`id` = 1 LIMIT 1   [1m [36mPublication Load (0.1ms) [0m   [1mSELECT `publications`.\* FROM `publications` WHERE `publications`.`id` = 1 LIMIT 1 [0m   [1m [35mPublisher Load (0.1ms) [0m  SELECT `publishers`.\* FROM `publishers` WHERE `publishers`.`id` = 1 LIMIT 1   [1m [36mWorkNameString Load (0.1ms) [0m   [1mSELECT
`work_name_strings`.\* FROM `work_name_strings` WHERE `work_name_strings`.`role` = 'Author' AND (`work_name_strings`.work_id = 1) ORDER BY position [0m   [1m [35mNameString Load (0.1ms) [0m  SELECT `name_strings`.\* FROM `name_strings` WHERE (`name_strings`.`id` = 1)   [1m [36mWorkNameString Load (0.1ms) [0m   [1mSELECT
`work_name_strings`.\* FROM `work_name_strings` WHERE `work_name_strings`.`role` = 'Editor' AND (`work_name_strings`.work_id = 1) ORDER BY position [0m   [1m [35mNameString Load (0.1ms) [0m  SELECT `name_strings`.\* FROM `name_strings` WHERE (`name_strings`.`id` = 2) Rendered attachments/forms/_form_content_file.html.haml (60169.6ms) Rendered attachments/new.html.haml within layouts/application (60179.1ms)
Completed   in 60459ms

ActionView::Template::Error (execution expired):
   3:     %h4="Attaching to #{@asset.class.to_s.underscore.humanize}:"

   4:     -# %span.asset= render :partial =>
"works/apa/#{@asset.class.name.to_s.underscore}", :locals => { :c => @asset }

   5:     - ce = WorkExport.new

   6:     %span.asset= ce.drive_csl("apa", @asset).html_safe

   7:

   8:   %fieldset

   9:     %legend="Content Files"

 app/models/work_export.rb:55:in `new'
 app/models/work_export.rb:55:in`load_csl'
 app/models/work_export.rb:19:in `drive_csl'
 app/views/attachments/forms/_form_content_file.html.haml:6
 app/views/attachments/forms/_form_content_file.html.haml:1:in
`_app_views_attachments_forms__form_content_file_html_haml__280639159__626938038_2802576'
 app/views/attachments/new.html.haml:25:in
# `_app_views_attachments_new_html_haml___467311490__626849978_0'

Not sure what is holding it up,

Mark

**Comment by hading** [comment]
I do get the same error when I try this on my local copy. Perhaps a problem in using the csl processor to translate into an export form? I may have touched something around this at some point, so it may be related to that, but I'm not sure.

**Comment by hading** [comment]
It appears to be sticking on creating a new csl parser. Not sure why.

**Comment by hading** [comment]
WorkExport seems to correctly make a URL to the csl file, and that file exists in public/csl_styles. However, in load_csl in WorkExport we don't seem to be able to use that url with Citeproc::CslParser.new to make a parser.

**Comment by hading** [comment]
I can, however, call Citproc::CslParser.new('http://localhost:3000/csl_styles/apa.csl') in the console and get a parser, which is odd. Need to run through the debugger again and check the url in the Rails app.

**Comment by hading** [comment]
when we try to open the url in csl_parser.rb (in the citation parser plugin) in the build method it looks like we might be hanging there, on this line:

 @document = REXML::Document.new(open(source))

May just need to rejigger this to fetch the csl properly from the URL. 

None of the code around any of this has changed significantly in a long time - it may be that there have been Rails changes that make this fail.

**Comment by hading** [comment]
Although I still don't understand why it would work in the console but not in Rails.

**Comment by hading** [comment]
It does indeed appear to be failing when the open-uri library tries to go out to fetch the csl file over the web. Still don't know why it works in the console but not in Rails. Possible solutions:
- use a different method to fetch over the web
- demand that all csl files are deposited locally and fetch them through the filesystem.

I may try the latter just to make sure that it works if I do that and then worry about whether I can web enable it. As things are now I'm not sure there is a convincing reason to do the latter, though.

**Comment by hading** [comment]
It does work properly if I fetch the csl from the filesystem. Offhand I don't see any convincing reason not to do it that way for now.

**Comment by hading** [comment]
Changed it so it reads the csl from the filesystem instead of via a web request. 
If necessary we could obviously cache this as well, but that seems like unnecessary complexity until it seems useful to do.
Also simplified the conversion of the format argument to a filename as we are currently using a simple convention to relate them - complexify it later if needed.
