### ISSUE TITLE
slowness verifying contributorships

### ISSUE THREAD

**Issue by hading** [BibApp/BibApp#23]
From an email from Sarah Shreeves:

I'm also finding that trying to verify contributorships take a long time - even just 10.

**Comment by hading** [comment]
This seems to have taken about 15-20 seconds (for 10) even on my development machine. I'll see if I can figure out what part of it is going slow.

**Comment by hading** [comment]
There is a _lot_ of SQL going on for this. Remains to see if I can cut down on it.

**Comment by hading** [comment]
The problem appears to be in the callbacks fired off after we update a contributorship. We get an update statement that 
sets the contributorship's contributorship_state_id and then there is a lot of stuff that happens after that in the refresh_contributorships method.

Some of this stuff originally used the (removed) save_without_callbacks stuff. It may be that we need to replicate that, or it may be that there are efficiency gains to be had so that we don't need to do that.

**Comment by hading** [comment]
I should also note that just in general there is a lot of stuff going that I believe has to do with authorization. I wonder if we could fix this up somehow. Maybe there is something that could be cached in a reasonable way.

**Comment by hading** [comment]
Made a change in Person#set_pen_names to cut down the number of queries needed there at the expense of making it a bit more complex.

However, I still think that maybe the best point of attack here is trying to do something about authorization. First see if I can confirm all the sql that I think is coming out of there really is and then perhaps figure out a way to cache it.

**Comment by hading** [comment]
Maybe these aren't actually to do with authorization. I'm just not used to seeing them. You get a lot of stuff like:

SQL (1.1ms)   SELECT a.attname, format_type(a.atttypid, a.atttypmod), d.adsrc, a.attnotnull
 FROM pg_attribute a LEFT JOIN pg_attrdef d
 ON a.attrelid = d.adrelid AND a.attnum = d.adnum
 WHERE a.attrelid = '"users"'::regclass
 AND a.attnum > 0 AND NOT a.attisdropped
 ORDER BY a.attnum

  User Load (4.0ms)  SELECT "users".\* FROM "users" WHERE "users"."id" = 1 LIMIT 1

The first part seems to be selecting the attributes that the user model has, and then is followed up by a query on the users table. This appears to be a common theme with these selects - and it is doing a lot of them. It may just be a development/production issue, though - it needs to look all this stuff up because it's not caching classes?

If so that wouldn't explain why this is so slow in production though.

**Comment by hading** [comment]
On my dev box to verify 10 records takes about 5 seconds in production, about 1/3-1/4 the time for in development. Most of this is spent in ContributorshipsController#act_on_multiple, but the logging is much less complete. 

The difficulty is that there's just not anything sticking out (in the more complete development logs) as something that is a big problem.

**Comment by hading** [comment]
I guess one nice side effect is that I found the New Relic gem which is pretty nice for profiling. I found another place where I could cut out quite a few queries, but I'm still doubtful that I'm going to be able to do all that much.

**Comment by hading** [comment]
Some progress - In the _displaying_ of the contributorship index there appears to be a real slowdown in the 
contributorships/_contributorship partial in the rendering of the shared/work partial. I speculate that the call to Index.work_to_solr_hash may figure into this.

A good test would be to rewrite that partial to use the actual work object instead of trying to use solr - however, this may be a bit complex as it in turn calls a number of other partials that involve using the solr form of data.

Maybe I can rig another test by only converting the first work and reusing that for all the others, just to get an idea of the speed effect.

**Comment by hading** [comment]
Or, actually, I could just suppress the partial actually displaying anything and see if the time is still big.

**Comment by hading** [comment]
Based on some crude work in the console we may be looking at about half a second for 10 work_to_solr_hash calls. Not necessarily insane, but significant and maybe removable.

**Comment by hading** [comment]
Display as is currently - 2383 ms
Display while doing work_to_solr_hash but then not displaying the corresponding partial - 1681 ms
Display while not displaying partial at all or doing work_to_solr_hash - 706 ms

So there is significant time spent both in doing the conversions and rendering the partial. Next in the display of shared/work let me remove the partials _it_ calls to see what happens.
All partials removed - 2310ms - so these appear to be fairly inconsequential.

**Comment by hading** [comment]
Thought there was a chance that doing include_stylesheet each time through the partial was a problem, but it doesn't seem to be.

**Comment by hading** [comment]
I'm a bit baffled by the fact that removing the subpartials from shared/work doesn't help very much, as almost nothing else is done in that view.

**Comment by hading** [comment]
Okay, this has me curious enough to start cutting pieces out of the shared/work partial to see if I can figure out how it's spending time in there.

**Comment by hading** [comment]
Of course these timings have all the problems generally associated with micro-benchmarks run one time on an uncontrolled machine, but nonetheless:

Remove everything - 2259ms
Excise everything in the partial's main %li, leaving only that - 2233 ms. So merely rendering the partial 10 times is taking 0.3 s, and the actual work it's doing about 0.4s.
Remove display of work - 2385ms
Remove nothing - 2801ms
Remove .links section - 2698ms
Remove sub-partials - 2731ms
Remove isbn/type/title - 2798 ms
Remove select checker - 2867 ms
Remove show_dupes and the-class - 2883 ms

So most of the time spent does appear to be going into the work, but I still don't understand the difference between removing everything from the partial and displaying (~2.3s) and doing work_to_solr_hash and then not displaying the partial at all (~1.7s). Is Rails really spending 600ms just displaying the same empty partial 10 times?

**Comment by hading** [comment]
I'm having trouble getting anywhere near replicating my 1681ms for doing work_to_solr_hash but not displaying the partial (it consistently comes in over 2200ms), so maybe that was off, in which case work_to_solr_hash may just be pretty bad. How hard will it be to replace it, though?

**Comment by hading** [comment]
I wish I thought there was a sane way to cache work_to_solr_hash, as that would be something - but with all the tentacles that solr has out, I'm not sure how to invalidate it.

It's not used all that much. I think I'll proceed with my initial experiment to remove it from this view and then see if I can trash all references to it. I think some of the other places it touches are other areas of noted slowness.

**Comment by hading** [comment]
First I do wonder if in:

doc = Solr::Importer::Mapper.new(SOLR_MAPPING).map(work)

it is the actual creation of the map or the creation of the Mapper that is taking a long time. If it's the latter we can just cache that somewhere and be good to go for now. That's a simple change, so it's worth trying that first.

**Comment by hading** [comment]
It doesn't really appear that this is the case, however. I'm running over the database on my test machine to get an idea how long the average construction of the map is. And the answer is: 43ms (using a cached mapped).  The min is 13ms and the max 7286ms. So yeah, killing this off could definitely help, provided that the views don't get correspondingly slower (and I don't think they would).

**Comment by hading** [comment]
Just for curiousity running on the test server:

average: 42ms min: 12ms max: 6015ms

**Comment by hading** [comment]
And (shhh!!) on the production server:

average: 36ms min: 8ms max: 1264ms median: 19ms

**Comment by hading** [comment]
I may have the views I need, or close to them, in the Sunspot branch already. Bears checking.

**Comment by hading** [comment]
Yep. Let's try plugging them in and see.

**Comment by hading** [comment]
Oh, wait, it's not that simple, because I may also use the Sunspot result. Still, I think it'll give me something close.

**Comment by hading** [comment]
Okay, I make minor use of the hit, most of which should be easy to trace back to the work, although the author/editor stuff might be a bit tricky.

**Comment by hading** [comment]
Without rendering the worktype subpartial redoing the view cut the time down to about 1.6 seconds, so saved about 0.7s, which is not too bad. I'd expect the percentage savings to be even better in production.

**Comment by hading** [comment]
I've done a little bit more stuff around this to perhaps cut out some redundancies and to avoid the possibility (which I still don't think was realizable, but now surely should not be) of an infinite loop. This in response to jstirnaman reporting slowness (and even timing out) with verifying contributorships. 

While the stuff I've commented about previously contributes to some slowness it really shouldn't  be enough to make a browser time out when verifying 10 works, which is why I'm trying the steps noted here.

Well, looking back at the data I guess it could be if there were a lot of works in the 10 that were taking longer times. That seems unlikely to me, but who knows?

**Comment by hading** [comment]
This is what I got from jstirnaman that made me start looking at this again today. Might as well record it here.

The delayed jobs _look_ slow to me, but I don't know for sure. Need to investigate more.

---

Our staff have been experiencing really slow response time while verifying works. The session may eventually times out during the wait, although the tasks complete.
In a recent example, the session timed out while the user was verifying 10 works. I don't have the production.log for the time period, but looking at delayed_job.log, I'm wondering if maybe the Solr commits are too frequent or if it's a database performance problem. Here's a 2 minute snippet of  delayed_job.log for the time period she experienced the problem.  There were also broken pipe errors in the Apache log, but not that's not uncommon.

Thanks,
Jason

2011-09-08T09:38:14-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Import#process_accepted_import completed after 431.3398
2011-09-08T09:38:22-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 7.4742
2011-09-08T09:38:25-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.4713
2011-09-08T09:38:33-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 7.7135
2011-09-08T09:38:39-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 6.4176
2011-09-08T09:38:48-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 9.0742
2011-09-08T09:38:52-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.3217
2011-09-08T09:38:59-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 7.2971
2011-09-08T09:39:03-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.8326
2011-09-08T09:39:11-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 7.8544
2011-09-08T09:39:14-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.1771
2011-09-08T09:39:21-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 6.8398
2011-09-08T09:39:24-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.3711
2011-09-08T09:39:33-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 8.5438
2011-09-08T09:39:36-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.0735
2011-09-08T09:39:45-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 9.4228
2011-09-08T09:39:49-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] JournalArticle#update_solr completed after 3.3718
2011-09-08T09:39:55-0500: [Worker(delayed_job host:dspace3-zone pid:12061)] Person#recalculate_unverified_contributorship_score completed after 6.5304

**Comment by hading** [comment]
May or may not be related, but I got a sporadic failure on a test while it was adding contributorships to a work:

1) Person finding related objects can return its most recent work
     Failure/Error: person.contributorships << (c = Factory.create(:contributorship, :person => person, :work => work))
     Timeout::Error:
       execution expired
     # ./lib/index.rb:196:in `optimize_index'
     # ./lib/index.rb:116:in`batch_index'
     # ./app/models/pen_name.rb:28:in `index_works'
     # ./spec/models/person_spec.rb:188:in`add_contributorship'
     # ./spec/models/person_spec.rb:89
     # ./spec/models/person_spec.rb:88:in `tap'
     # ./spec/models/person_spec.rb:88
     # ./spec/models/person_spec.rb:87:in`times'
     # ./spec/models/person_spec.rb:87:in `each'
     # ./spec/models/person_spec.rb:87:in`collect'
     # ./spec/models/person_spec.rb:87
