### ISSUE TITLE
error changing group name

### ISSUE THREAD

**Issue by hading** [BibApp/BibApp#60]
Reported by Claudia Jürgen

---

on both the master and i18n branch I get an internal error when trying to change the name of a group with memberships and works associated.

groups/10-Lehrstuhl_I_Analysis

Completed 500 Internal Server Error in 468ms

ActiveRecord::ReadOnlyRecord (ActiveRecord::ReadOnlyRecord):
  app/models/work.rb:385:in `set_for_index_and_save'
  lib/solr_updater.rb:17:in`reindex_associated_works'
  lib/solr_updater.rb:16:in `reindex_associated_works'
  lib/solr_updater.rb:6:in`reindex_after_save'
  app/models/index_observer.rb:13:in `after_save'

Claudia

**Comment by hading** [comment]
Reproduced. 

I suspect this will be easy to fix (just reload the works to make them not read-only). It may be more difficult to actually understand.

**Comment by hading** [comment]
Yes, that works. Also trying to delay each calls to Work.set_for_index_and_save (which also hits a lot of callbacks and makes Rails return to the user very slowly). Need to see what happens here. I'm a bit afraid that there is a rabbit hole of callbacks happening.

**Comment by hading** [comment]
Maybe not. It may just be burning a lot of batch_index works on my dev machine that have accumulated over time.

**Comment by hading** [comment]
Even so on a group with a lot of works delaying is time consuming if done simply - try moving it up the call chain a little bit.

**Comment by hading** [comment]
Okay, It's patched more or less as documented above. Since we delay earlier we can also simplify the code that does the reindexing - no need to fool around with batching, since it's already in the background.
