### ISSUE TITLE
error viewing deposit attachments

### ISSUE THREAD

**Issue by hading** [BibApp/BibApp#77]
reported by cjuergen:

---

while trying to connect our test DSpace Repository with the Test Bibapp installation I ran into this error, trying to view an attachement:

Started GET "/en/admin/deposit_via_sword?work_id=474" for 129.217.135.208 at Mon Jan 16 13:49:45 +0100 2012
  Processing by AdminController#deposit_via_sword as HTML
  Parameters: {"locale"=>"en", "work_id"=>"474"}
  Rendered works/_epdcx.mets.builder (294.7ms)
Rendered works/_package.mets.builder (319.3ms)
Completed 500 Internal Server Error in 4328ms

NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]):
  lib/sword_1_3_adapter.rb:35:in `send_sword_package'
  lib/sword_1_3_adapter.rb:82:in`with_mets_package'
  lib/sword_1_3_adapter.rb:56:in `with_mets_package'
  lib/sword_1_3_adapter.rb:26:in`send_sword_package'
  app/controllers/admin_controller.rb:28:in `deposit_via_sword'

The servicedocument is ok and the uploaded file is actually there. The work with the deposit attachement is listed in the admin/ready_to_archive and is viewable s via http://vmx012.itmc.tu-dortmund.de:3000/attachments/0000/0047/Kaninchen_Knoblauch.pdf.

Never used Sword before, so this is new territory for me.

Claudia 

---

Don't have any idea about this one off hand.

**Comment by hading** [comment]
I want to take a look at Claudia's sword.yml file. It looks like maybe it's trying to do the client.config['default_collection_url'] piece and failing, which could happen if there is a config problem, for example if there is no stanza for the environment.

I'm hoping it's that trivial.

**Comment by hading** [comment]
The snippet of config that Claudia sent looked okay to me. I'm going to try to get more information. It really looks like the SWORD client isn't getting configured, but I want to confirm that. 

If not then I'm really not sure why, as I don't see anything that ought to be preventing it. If it turns out to be the case I may try to get Claudia's full config file (sans passwords) as an attachment and see if something is going on with the reading in of the YAML.

**Comment by hading** [comment]
More info from Claudia. With a bit of debugging code in place:

yes on the test server we are running development. The config is identical for all three environments.

Changed lib/sword_1_3_adapter.rb as you suggested, this is the result:

ENV: development
SWORDCONFIG: ---
debug_mode: true
username: doe@versanet.de
default_collection_url: https://eldorado2.tu-dortmund.de/handle/2003/25781
service_doc_url: https://eldorado2.tu-dortmund.de/sword/servicedocument
password: ValidPassword
Completed 500 Internal Server Error in 5107ms

Net::HTTPServerException (405 "Method Not Allowed"):
  lib/sword_1_3_adapter.rb:39:in `send_sword_package'
  lib/sword_1_3_adapter.rb:86:in`with_mets_package'
  lib/sword_1_3_adapter.rb:60:in `with_mets_package'
  lib/sword_1_3_adapter.rb:26:in`send_sword_package'
  app/controllers/admin_controller.rb:28:in `deposit_via_sword'

We are using DSpace 1.6.1 with Sword 1.3.

Claudia

---

It looks like the default_collection_url is set fine. This is a different error, though, a 405 HTTP error. We'll see what we can do with that.

**Comment by hading** [comment]
This is solved. The SWORD config file needs the url for sword deposit as default_collection_url, not the viewing url for the collection. I've noted this in sword.yml.example. Unfortunately the name isn't totally clear about that.
